import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      xxl: '1536px',
    },
    fontSize: {
      xs: ['13px', '15px'],
      s: ['14px', '16px'],
      m: ['15px', '18px'],
      l: ['17px', '24px'],
      xl: ['20px', '24px'],
      '2xl': ['23px', '28px'],
      '3xl': ['25px', '30px'],
      '4xl': ['30px', '38px'],
    },
    fontFamily: {
      primary: [
        '-apple-system',
        'BlinkMacSystemFont',
        'var(--font-inter)',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
    },
    extend: {
      colors: {
        'theme-dark-primary': 'rgba(var(--theme-dark-primary))',
        'theme-dark-background': 'rgba(var(--theme-dark-background))',
        'theme-dark-foreground': 'rgba(var(--theme-dark-foreground))',
        'theme-dark-text': 'rgba(var(--theme-dark-text))',
        'theme-light-primary': 'rgba(var(--theme-light-primary))',
        'theme-light-background': 'rgba(var(--theme-light-background))',
        'theme-light-foreground': 'rgba(var(--theme-light-foreground))',
        'theme-light-text': 'rgba(var(--theme-light-text))',
        'theme-midnightBlue-primary': 'rgba(var(--theme-midnightBlue-primary))',
        'theme-midnightBlue-background': 'rgba(var(--theme-midnightBlue-background))',
        'theme-midnightBlue-foreground': 'rgba(var(--theme-midnightBlue-foreground))',
        'theme-midnightBlue-text': 'rgba(var(--theme-midnightBlue-text))',
        'theme-tokyoNight-primary': 'rgba(var(--theme-tokyoNight-primary))',
        'theme-tokyoNight-background': 'rgba(var(--theme-tokyoNight-background))',
        'theme-tokyoNight-foreground': 'rgba(var(--theme-tokyoNight-foreground))',
        'theme-tokyoNight-text': 'rgba(var(--theme-tokyoNight-text))',
        primary: 'rgba(var(--primary))',
        black: 'rgba(var(--black))',
        emerald: 'rgba(var(--emerald))',
        pink: 'rgba(var(--pink))',
        'error-1': 'rgba(var(--error-1))',
        tooltip: 'var(--tooltip)',
        backdrop: 'var(--backdrop)',
        focus: 'var(--focus)',
        'button-background-gray': 'rgba(var(--button-background-gray))',
        background: 'rgba(var(--background))',
        foreground: 'rgba(var(--foreground))',
        'text-1': 'rgba(var(--text-1))',
        'text-2': 'rgba(var(--text-2))',
        'border-1': 'rgba(var(--border-1))',
        'border-2': 'rgba(var(--border-2))',
        skeleton: 'var(--skeleton)',
        'skeleton-swipe': 'var(--skeleton-swipe)',
        'input-background': 'var(--input-background)',
        'switch-dot': 'rgba(var(--switch-dot))',
        'switch-background-inactive': 'rgba(var(--switch-background-inactive))',
        'dropdown-background': 'rgba(var(--dropdown-background))',
        'dropdown-border': 'rgba(var(--dropdown-border))',
      },
      opacity: {
        '07': '0.07',
        '10': '0.1',
        '15': '0.15',
        '16': '0.16',
        '22': '0.22',
        '60': '0.6',
        '65': '0.65',
        '70': '0.7',
        '75': '0.75',
        '80': '0.8',
        '85': '0.85',
      },
      brightness: {
        '15': '0.15',
        '60': '0.6',
        '65': '0.65',
        '70': '0.7',
        '75': '0.75',
        '80': '0.8',
        '85': '0.85',
      },
      scale: {
        '05': '0.05',
        '10': '0.1',
        '15': '0.15',
        '60': '0.6',
        '65': '0.65',
        '70': '0.7',
        '75': '0.75',
        '80': '0.8',
        '85': '0.85',
      },
      keyframes: {
        swipe: {
          '0%': {
            left: '-100%',
          },
          '100%': {
            left: '100%',
          },
        },
        appear: {
          '0%': {
            opacity: '0',
          },
          '100%': {
            opacity: '1',
          },
        },
        logoAppear: {
          '0%': {
            opacity: '0',
            scale: '0.50',
          },
          '50%': {
            opacity: '1',
            scale: '1.25',
          },
          '100%': {
            scale: '1',
          },
        },
      },
      animation: {
        appear: 'appear .3s ease-out',
        spin: 'appear .3s ease-out, spin .7s linear infinite',
        swipe: 'swipe 1.1s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        logoAppear: 'logoAppear .4s',
      },
    },
  },
  plugins: [],
} satisfies Config;
