// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from './enums';

export type GetCurrentUserResponse = {
  isFollowing: boolean;
  followersCount: bigint;
  followingCount: bigint;
  id: string;
  name: string;
  screenName: string;
  email: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  url: string | null;
  role: Role;
  isVerified: boolean;
  verifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type LoginRequest = { emailOrScreenName: string; password: string };

export type LoginResponse = {
  isFollowing: boolean;
  followersCount: bigint;
  followingCount: bigint;
  id: string;
  name: string;
  screenName: string;
  email: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  url: string | null;
  role: Role;
  isVerified: boolean;
  verifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type RegisterRequest = { name: string; screenName: string; email: string; password: string };
