// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from './user';

export type LoginRequest = { emailOrScreenName: string; password: string };

export type LoginResponse = { user: User };

export type RegisterRequest = { name: string; screenName: string; email: string; password: string };
