// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConversationControl = 'ALL' | 'COMMUNITY' | 'BY_INVITATION';

export type PostMediaType = 'PHOTO' | 'VIDEO';

export type Role = 'ADMIN' | 'MODERATOR' | 'USER';
