// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationControl } from './enums';
import type { PostMediaType } from './enums';
import type { Cursor } from './global';
import type { BaseUser } from './user';

export type GlobalTimelineRequest = { cursor: Cursor | null; limit: bigint | null };

export type GlobalTimelineResponse = { posts: Array<Post>; nextCursor: Cursor | null };

export type Post = {
  author: BaseUser;
  media: Array<PostMedia>;
  isAuthor: boolean;
  isLiked: boolean;
  likesCount: bigint;
  repliesCount: bigint;
  editedAt: Date | null;
  id: string;
  text: string;
  authorId: string;
  hashtags: Array<string | null> | null;
  conversationControl: ConversationControl;
  createdAt: Date;
  updatedAt: Date;
};

export type PostMedia = {
  id: string;
  url: string;
  width: number;
  height: number;
  type: PostMediaType;
  postId: string;
  userId: string;
  createdAt: Date;
};
