// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationControl } from './enums';
import type { PostMediaType } from './enums';
import type { Cursor } from './global';
import type { BaseUser } from './user';

export type CreatePostRequest = { text: string; media: File[] };

export type CreatePostResponse = {
  author: BaseUser;
  media: Array<PostMedia>;
  isAuthor: boolean;
  isLiked: boolean;
  likesCount: number;
  repliesCount: number;
  editedAt: Date | null;
  id: string;
  text: string;
  authorId: string;
  hashtags: Array<string | null> | null;
  conversationControl: ConversationControl;
  createdAt: Date;
  updatedAt: Date;
};

export type DeletePostParams = { id: string };

export type DeletePostResponse = { id: string; message: string };

export type GetGlobalTimelineParams = { cursor: Cursor | null; limit: number | null };

export type GetGlobalTimelineResponse = { posts: Array<Post>; nextCursor: Cursor | null };

export type GetPostDetailsParams = { postId: string };

export type GetPostDetailsResponse = {
  author: BaseUser;
  media: Array<PostMedia>;
  isAuthor: boolean;
  isLiked: boolean;
  likesCount: number;
  repliesCount: number;
  editedAt: Date | null;
  id: string;
  text: string;
  authorId: string;
  hashtags: Array<string | null> | null;
  conversationControl: ConversationControl;
  createdAt: Date;
  updatedAt: Date;
};

export type GetUserLikesParams = {
  screenName: string;
  cursor: Cursor | null;
  limit: number | null;
};

export type GetUserLikesResponse = {
  likes: Array<PostWithLike>;
  nextCursor: Cursor | null;
  totalCount: number;
};

export type GetUserMediaParams = {
  screenName: string;
  cursor: Cursor | null;
  limit: number | null;
};

export type GetUserMediaResponse = {
  posts: Array<Post>;
  nextCursor: Cursor | null;
  totalCount: number;
};

export type GetUserPostsParams = {
  screenName: string;
  cursor: Cursor | null;
  limit: number | null;
};

export type GetUserPostsResponse = {
  posts: Array<Post>;
  nextCursor: Cursor | null;
  totalCount: number;
};

export type Post = {
  author: BaseUser;
  media: Array<PostMedia>;
  isAuthor: boolean;
  isLiked: boolean;
  likesCount: number;
  repliesCount: number;
  editedAt: Date | null;
  id: string;
  text: string;
  authorId: string;
  hashtags: Array<string | null> | null;
  conversationControl: ConversationControl;
  createdAt: Date;
  updatedAt: Date;
};

export type PostLike = { id: string; postId: string; userId: string; createdAt: Date };

export type PostMedia = {
  id: string;
  url: string;
  width: number;
  height: number;
  type: PostMediaType;
  postId: string;
  userId: string;
  createdAt: Date;
};

export type PostWithLike = { like: PostLike; post: Post };

export type UpdatePostParams = { id: string };

export type UpdatePostRequest = { text: string; removedMediaIds: string[] | null; media: File[] };

export type UpdatePostResponse = {
  author: BaseUser;
  media: Array<PostMedia>;
  isAuthor: boolean;
  isLiked: boolean;
  likesCount: number;
  repliesCount: number;
  editedAt: Date | null;
  id: string;
  text: string;
  authorId: string;
  hashtags: Array<string | null> | null;
  conversationControl: ConversationControl;
  createdAt: Date;
  updatedAt: Date;
};
