// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from './enums';

export type CurrentUser = {
  id: string;
  name: string;
  screenName: string;
  email: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  url: string | null;
  role: Role;
  isVerified: boolean;
  verifiedAt: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type User = {
  id: string;
  name: string;
  screenName: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  url: string | null;
  role: Role;
  isVerified: boolean;
  verifiedAt: string | null;
  createdAt: Date;
  updatedAt: Date;
};
