// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from './enums';

export type BaseUser = {
  id: string;
  name: string;
  screenName: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  url: string | null;
  role: Role;
  isVerified: boolean;
  verifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type CurrentUser = {
  isFollowing: boolean;
  followersCount: number;
  followingCount: number;
  id: string;
  name: string;
  screenName: string;
  email: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  url: string | null;
  role: Role;
  isVerified: boolean;
  verifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type Follow = { id: string; followerId: string; followingId: string; createdAt: Date };

export type FollowUserParams = { userId: string };

export type FollowUserResponse = { id: string; message: string };

export type GetProfileDetailsParams = { screenName: string };

export type GetProfileDetailsResponse = {
  isFollowing: boolean;
  followersCount: number;
  followingCount: number;
  id: string;
  name: string;
  screenName: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  url: string | null;
  role: Role;
  isVerified: boolean;
  verifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type ProfileUser = {
  isFollowing: boolean;
  followersCount: number;
  followingCount: number;
  id: string;
  name: string;
  screenName: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  url: string | null;
  role: Role;
  isVerified: boolean;
  verifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type UnfollowUserParams = { userId: string };

export type UnfollowUserResponse = { id: string; message: string };

export type UpdateProfileRequest = {
  name: string;
  description: string;
  url: string | null;
  removeBanner: boolean | null;
  avatarFile: File | null;
  bannerFile: File | null;
};
