import '../globals.css';

import type { ReactNode } from 'react';

import SidebarMenu from '@/components/organisms/SidebarMenu';
import type { Locale } from '@/constants/locales';
import { routing } from '@/i18n/routing';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';

import Providers from './providers';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
  params: Promise<{ locale: Locale }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} className={inter.variable} suppressHydrationWarning>
      <body>
        <Providers locale={locale} messages={messages}>
          <div className='relative mx-auto flex min-h-screen w-full md:max-w-[688px] lg:max-w-[1008px] xl:max-w-[1265px]'>
            <SidebarMenu />
            <main className='relative flex w-full grow gap-[30px]'>
              <div className='flex w-full max-w-full flex-col pb-24 sm:max-w-[600px] sm:border-x sm:border-border-1 sm:pb-48'>
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
